### ISSUE TITLE
Feature request: disable despawn in options (permanent)

### ISSUE THREAD

**Issue by oczkers** [fadster/TrafficManager_ImprovedAI#2]
So we don't have to enable this every time game is started/save is loaded.

**Comment by fadster** [comment]
I thought about saving the setting for this option along with all the other parameters but decided not to because some people might not remember having disabled it. I'll think about it.

**Comment by armarayo** [comment]
The vehicles especially cars are designed to despawn eventually ... after a long lull, a loooong lull.

**Comment by fadster** [comment]
Will not implement for reason stated above.
