### ISSUE TITLE
With After Dark, Enabling TM+IAI causes intersections to not render properly

### ISSUE THREAD

**Issue by WillFa** [fadster/TrafficManager_ImprovedAI#4]
![image](https://cloud.githubusercontent.com/assets/156476/10088075/256bf422-62e6-11e5-9cf3-00b4755d6289.png)

Notice the roundabout is overlapping, and not intersecting.
Notice the horizontal 6-lane road has its lane configuration loaded.
Notice the vertical 6-lane road does not. (should be F, F, R like the horizontal)

This happens with NExt roads and Enhanced Road Heights ramps, from what I've noticed.

**Comment by fadster** [comment]
I can't reproduce this and I don't see how this mod would be responsible as it doesn't affect road placement. Do you have the same problem without the mod enabled? My feeling is this is an issue with Network Extensions or Enhanced Road Heights.

**Comment by WillFa** [comment]
Game loads correctly with TM+IAI disabled. Enhanced Road Heights has been disabled since pre-AD. 

Using these mods: 
![image](https://cloud.githubusercontent.com/assets/156476/10112046/48c697ae-63a6-11e5-90bc-b27cd68903a8.png)

The Game Loads fine.
![image](https://cloud.githubusercontent.com/assets/156476/10112188/1ddb809e-63a7-11e5-90f2-bed807ae9ec7.png)

Turning on TM+IAI:
![image](https://cloud.githubusercontent.com/assets/156476/10112095/90ac527a-63a6-11e5-9ecc-5a67f5989072.png)

The game doesn't load fine.
![image](https://cloud.githubusercontent.com/assets/156476/10112143/e9112314-63a6-11e5-9f1d-41a22b245ef4.png)

(Serializing and Deserializing the roads while loading the configuration does re-place/update the roads, btw. Perhaps it's a race condition where TM+IAI is loading prior to NExt fully being loaded. OnLoadData just has a 2 second delay before calling OnLoadDataTimed. Perhaps increasing that delay, or moving the code in OnLoadDataTimed to OnLevelLoaded works around it? I know you don't like mucking about in 'legacy' code, but perhaps it's warranted.)

**Comment by armarayo** [comment]
Basic compatibility should come first, after that with the highwaylaneproject what is known as Network Extensions too.. so much focus on highways, why not rail? overground metro/tram? :)

**Comment by WillFa** [comment]
Hey Aramarayo, What does your comment about a different mod not implementing the trains you want  have to do with this mod applying its configuration at the wrong time?

**Comment by armarayo** [comment]
Sorry, of course I want it to be compatible, but if the option(s) isn't/aren't viable enough at this time, then it might be a no go.

**Comment by fadster** [comment]
I'll take a look, I admit I don't fully understand the purpose of this 2 second delay. I assume it's to allow all roads to be loaded before lane changes are made, in which case the value '2' would be entirely arbitrary, which is not a good thing. Perhaps Network Extensions is taking too long to load its roads? I say this because TM has always worked with T++ which does similar vanilla road replacement.

**Comment by WillFa** [comment]
I agree the 2 is arbitrary... and honestly, when have you ever seen CSL load a game in 2 seconds? :) Vanilla, no assets, empty map takes more than 2 seconds to load...
