### ISSUE TITLE
Do you mind if I make Japanse localized version of this mod?

### ISSUE THREAD

**Issue by akira-ishizaki** [fadster/TrafficManager_ImprovedAI#7]
Hello. This mod is very useful. But I'm Japanese.
Do you mind if I make Japanse localized version of this mod and share on my Steam Workshop?

**Comment by fadster** [comment]
Hello,

Sure, go ahead!

- Fady

**Comment by akira-ishizaki** [comment]
I have shared here.
http://steamcommunity.com/sharedfiles/filedetails/?id=563720449
Sorry to be so late in contacting you.

**Comment by fadster** [comment]
Sorry for the late reply, thanks for your contribution! :)
